/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scl;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.FileOutputStream;
import java.io.FileInputStream;
import java.io.IOException;

import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;
import org.antlr.v4.runtime.tree.ParseTreeWalker;

import biweekly.ICalendar;

public class App {
    public static void main(String[] args) {
        // TODO: add command-line parameters <2021-04-27, David Deng> //
        // String testInput 
        //     = "event Chorale\n"
        //         + "from: \"May 1, 2021 7:00PM\"\n"
        //         + "to: \"May 1, 2021 10:00PM\"\n"
        //     + "\n";

        SCLLexer lexer;
        try {
            // lexer = new SCLLexer(CharStreams.fromString(testInput));
            lexer = new SCLLexer(CharStreams.fromFileName("test.scl"));
        } catch (IOException e) {
            System.out.println("Failed to open file. " + e.toString());
            return;
        }
        CommonTokenStream tokens = new CommonTokenStream(lexer);
        SCLParser parser = new SCLParser(tokens);
        parser.setBuildParseTree(true); // tell ANTLR to build a parse tree
        ParseTree tree = parser.file();

        ParseTreeWalker walker = new ParseTreeWalker();
        PropReader reader = new PropReader();
        walker.walk(reader, tree);
        ICalendar ical = reader.getCalendar();
        System.out.println("Calendar content below ------------");
        try {
            FileOutputStream out = new FileOutputStream("test.ics");
            ical.write(out);
        } catch (IOException e) {
            System.out.println("Failed to write to file. " + e.toString());
        }
    }
}
